import cron from 'node-cron';
import nodemailer from 'nodemailer';
import { db } from '../db/index.js';
import { studentsTable, dailySnapshots } from '../db/schema.js';
import { eq, sql, desc, and } from 'drizzle-orm';

// Setup Nodemailer transporter
const transporter = nodemailer.createTransport({
    service: 'gmail', // You can change this to any SMTP provider
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
    }
});

export const runWeeklyReport = async () => {
    console.log("Starting weekly top coder email generation...");
    
    try {
        // Find latest snapshot date
        const latestDate = await db
            .select({ date: sql<string>`MAX(${dailySnapshots.date})`.as('max_date') })
            .from(dailySnapshots);
            
        if (!latestDate[0] || !latestDate[0].date) {
            console.log("No snapshot data available to generate report.");
            return;
        }

        const maxDateStr = latestDate[0].date;

        // Fetch top 3 students based on progress THIS WEEK (lcWeekTotal + gfgWeekTotal)
        const topStudents = await db
            .select({
                name: studentsTable.name,
                rollNumber: studentsTable.rollNumber,
                lcWeekTotal: dailySnapshots.lcWeekTotal,
                gfgWeekTotal: dailySnapshots.gfgWeekTotal,
                totalWeeklySolved: sql<number>`COALESCE(${dailySnapshots.lcWeekTotal}, 0) + COALESCE(${dailySnapshots.gfgWeekTotal}, 0)`.as('total_weekly'),
                totalSolved: sql<number>`COALESCE(${dailySnapshots.lcTotal}, 0) + COALESCE(${dailySnapshots.gfgTotal}, 0)`.as('total_solved')
            })
            .from(studentsTable)
            .innerJoin(
                dailySnapshots,
                and(
                    eq(studentsTable.id, dailySnapshots.studentId),
                    eq(dailySnapshots.date, sql`CAST(${maxDateStr} AS DATE)`)
                )
            )
            .orderBy(
                desc(sql`total_weekly`),
                desc(sql`total_solved`)
            )
            .limit(3);

        if (topStudents.length === 0) {
            console.log("No students found for weekly report.");
            return;
        }

        // Generate HTML Email
        const htmlContent = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaec; border-radius: 10px;">
                <h2 style="color: #4F46E5; text-align: center;">🏆 Weekly Coding Champions 🏆</h2>
                <p style="text-align: center; color: #555;">Here are the top 3 most active students this week across LeetCode and GeeksforGeeks!</p>
                <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
                
                ${topStudents.map((s, i) => `
                    <div style="margin-bottom: 15px; padding: 15px; background-color: #f9fafb; border-radius: 8px;">
                        <h3 style="margin: 0 0 5px 0; color: #111;">#${i + 1} ${s.name} (${s.rollNumber})</h3>
                        <p style="margin: 0; color: #666;">
                            <strong>Total Problems Solved This Week:</strong> ${s.totalWeeklySolved}<br/>
                            <small>LeetCode: ${s.lcWeekTotal} | GeeksforGeeks: ${s.gfgWeekTotal}</small>
                        </p>
                    </div>
                `).join('')}
                
                <p style="text-align: center; margin-top: 30px; font-size: 12px; color: #999;">
                    Generated by All Eyes On You - Placement Cell Tracker
                </p>
            </div>
        `;

        // Send Email
        const mailOptions = {
            from: process.env.EMAIL_USER,
            to: process.env.ADMIN_EMAIL || process.env.EMAIL_USER,
            subject: '🏆 Weekly Coding Leaderboard Report',
            html: htmlContent
        };

        // Check if credentials are set before attempting to send
        if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
            console.log("Email credentials missing in .env. Skipping actual email dispatch. Top students:");
            console.log(topStudents);
            return;
        }

        await transporter.sendMail(mailOptions);
        console.log("Weekly report email sent successfully!");

    } catch (error) {
        console.error("Failed to generate or send weekly report:", error);
    }
};

// Schedule to run every Sunday at 08:00 AM
export const startWeeklyEmailCron = () => {
    cron.schedule('0 8 * * 0', () => {
        runWeeklyReport();
    });
    console.log("Weekly Email Cron Job Scheduled (Sundays 8:00 AM)");
};
